# Generated by Django 4.2.3 on 2024-04-25 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceName', models.CharField(max_length=50)),
                ('deviceType', models.CharField(max_length=30)),
                ('deviceQuantity', models.IntegerField()),
                ('deviceAudit', models.DateField()),
                ('deviceLocation', models.CharField(max_length=30)),
                ('deviceStatus', models.CharField(blank=True, max_length=40)),
                ('deviceComments', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceDetailName', models.CharField(default=' ', max_length=50)),
                ('deviceSerial', models.CharField(max_length=20)),
                ('deviceRAM', models.CharField(blank=True, max_length=40)),
                ('deviceCPU', models.CharField(blank=True, max_length=40)),
                ('deviceGPU', models.CharField(blank=True, max_length=40)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.device')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingType', models.CharField(max_length=50)),
                ('dueDate', models.DateField()),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.device')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
