# Generated by Django 5.0.4 on 2024-04-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDOB', models.DateField()),
                ('userEmail', models.CharField(max_length=200)),
                ('userPassword', models.CharField(max_length=200)),
            ],
        ),
    ]
