# Generated by Django 5.0.4 on 2024-04-22 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_device_devicedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userPermissions',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingType', models.CharField(max_length=50)),
                ('dueDate', models.DateField()),
                ('deviceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.device')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.users')),
            ],
        ),
    ]
