# Generated by Django 5.0.4 on 2024-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_users_userpermissions_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
