# Generated by Django 5.0.4 on 2024-04-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDOB', models.DateField()),
                ('userEmail', models.CharField(max_length=200)),
                ('userPassword', models.CharField(max_length=200)),
                ('userPermissions', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
