# Generated by Django 5.0.4 on 2024-04-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_users_alter_booking_userid_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userName',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
