# Generated by Django 5.0.4 on 2024-04-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_alter_booking_userid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deviceID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Site.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
